version: "3.8"
name: aid-compass-scheduled-tasks-service
services:
  aid-compass-scheduled-tasks-app:
    container_name: aid-compass-scheduled-tasks-app
    build:
      context: .
      dockerfile: Dockerfile
    image: aid-compass-scheduled-tasks-app
    depends_on:
      - aid-compass-scheduled-tasks-postgresql
    ports:
      - "8081:8080"
    env_file:
      - .docker_env

  aid-compass-scheduled-tasks-postgresql:
    container_name: aid-compass-scheduled-tasks-postgresql
    image: postgres:16.1-alpine3.19
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: aid_compass_scheduled_tasks_database
    ports:
      - "5433:5432"